# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('display', models.CharField(max_length=100)),
                ('field_type', models.IntegerField(choices=[(0, 'INT'), (1, 'FLOAT'), (2, 'VARCHAR'), (3, 'BOOL'), (4, 'DATETIME')])),
                ('required', models.BooleanField(default=False)),
                ('multiple', models.BooleanField(default=False)),
                ('unique', models.BooleanField(default=False)),
                ('default', models.CharField(max_length=200)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('display', models.CharField(max_length=200)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Entity')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Field')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Schema'),
        ),
        migrations.AddField(
            model_name='entity',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Schema'),
        ),
    ]
